-- MySQL Script generated by MySQL Workbench
-- Fri May 27 12:43:44 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`klient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`klient` (
  `idklient` INT NOT NULL AUTO_INCREMENT,
  `imię` VARCHAR(45) NULL,
  `nazwisko` VARCHAR(45) NULL,
  `telefon` VARCHAR(45) NULL,
  `adres` VARCHAR(45) NULL,
  PRIMARY KEY (`idklient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`towar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`towar` (
  `idtowar` INT NOT NULL,
  `kod` VARCHAR(45) NULL,
  `nazwa` VARCHAR(45) NULL,
  `stan` VARCHAR(45) NULL,
  `opis` VARCHAR(45) NULL,
  `cena` FLOAT NULL,
  PRIMARY KEY (`idtowar`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`zamówienie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`zamówienie` (
  `idzamówienie` INT NOT NULL,
  `data` DATETIME(6) NULL,
  `ilość` INT NOT NULL,
  `towar_idtowar` INT NOT NULL,
  `klient_idklient` INT NOT NULL,
  PRIMARY KEY (`idzamówienie`, `towar_idtowar`, `klient_idklient`),
  INDEX `fk_zamówienie_towar_idx` (`towar_idtowar` ASC) VISIBLE,
  INDEX `fk_zamówienie_klient1_idx` (`klient_idklient` ASC) VISIBLE,
  CONSTRAINT `fk_zamówienie_towar`
    FOREIGN KEY (`towar_idtowar`)
    REFERENCES `mydb`.`towar` (`idtowar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zamówienie_klient1`
    FOREIGN KEY (`klient_idklient`)
    REFERENCES `mydb`.`klient` (`idklient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
